services:
  kafka-mirror-maker:
    image: apache/kafka:3.9.0
    container_name: kafka-mirror-maker
    ports:
      - "9093:9093"
    environment:
      KAFKA_HEAP_OPTS: "-Xms512m -Xmx512m"
      SOURCE_BROKER: ${SOURCE_BROKER}
      TARGET_BROKER: ${TARGET_BROKER}
    volumes:
      - ./configs/MM2-Ativo-Passivo.properties:/opt/kafka/config/MM2-Ativo-Passivo.properties
    entrypoint: |
      sh -c "
      cp /opt/kafka/config/MM2-Ativo-Passivo.properties /tmp/MM2-Ativo-Passivo.properties &&
      sed -i 's|SOURCE_BROKER|'$SOURCE_BROKER'|g' /tmp/MM2-Ativo-Passivo.properties &&
      sed -i 's|TARGET_BROKER|'$TARGET_BROKER'|g' /tmp/MM2-Ativo-Passivo.properties &&
      /opt/kafka/bin/connect-mirror-maker.sh /tmp/MM2-Ativo-Passivo.properties
      "
    depends_on:
      - prometheus
      - kafka-exporter

  kafka-exporter:
    image: bitnami/kafka-exporter:latest
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    environment:
      KAFKA_BROKERS: ${SOURCE_BROKER},${TARGET_BROKER}
    command: ["--kafka.server=${KAFKA_BROKERS}"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${SOURCE_BROKER}
      - KAFKA_CLUSTERS_0_NAME=teste-1
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=${TARGET_BROKER}
      - KAFKA_CLUSTERS_1_NAME=teste-2