version: '3.9'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=$SOURCE_BROKER
      - KAFKA_CLUSTERS_0_NAME=teste-1
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=$TARGET_BROKER
      - KAFKA_CLUSTERS_1_NAME=teste-2
      - KAFKA_HEAP_OPTS=-Xms512m -Xmx512m
      - JAVA_OPTS=-Xms512m -Xmx512m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning

  jmx-exporter:
    image: prom/jmx-exporter:latest
    container_name: jmx-exporter
    ports:
      - "5556:5556"
    volumes:
      - ./jmx-config.yml:/config/config.yml
    command: --config.file=/config/config.yml
    environment:
      - JAVA_OPTS=-javaagent:/jmx_prometheus_javaagent.jar=5556:/config/config.yml

volumes:
  grafana-data: