lowercaseOutputName: true
rules:
  - pattern: "kafka.connect<type=connector-task-metrics><>(.*)"
    name: "kafka_connect_task_$1"
    type: GAUGE
  - pattern: "kafka.connect.mirror<type=MirrorSourceConnector,name=(.*)><>(.*)"
    name: "kafka_mirror_$1_$2"
    type: GAUGE
  - pattern: "kafka.connect.mirror<type=MirrorCheckpointConnector,name=(.*)><>(.*)"
    name: "kafka_checkpoint_$1_$2"
    type: GAUGE