global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter-source'
    static_configs:
      - targets: ['kafka-exporter-source:9308']
        labels:
          cluster: 'source'

  - job_name: 'kafka-exporter-target'
    static_configs:
      - targets: ['kafka-exporter-target:9309']
        labels:
          cluster: 'target'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']